"""Init

Revision ID: 14267f5434e2
Revises: d193258315ee
Create Date: 2022-12-13 09:22:03.156742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14267f5434e2'
down_revision = 'd193258315ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
