"""Init

Revision ID: 2e8d5992aacb
Revises: 7e9cb9fee50a
Create Date: 2022-12-13 09:20:11.996001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e8d5992aacb'
down_revision = '7e9cb9fee50a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
