"""Init

Revision ID: 406dc6d1479c
Revises: 671206b30136
Create Date: 2022-12-13 08:44:16.183644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '406dc6d1479c'
down_revision = '671206b30136'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
