"""Init

Revision ID: 7e9cb9fee50a
Revises: a78868cea02b
Create Date: 2022-12-13 09:07:14.456211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e9cb9fee50a'
down_revision = 'a78868cea02b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
