"""Init

Revision ID: 671206b30136
Revises: bbc6b0512ae2
Create Date: 2022-12-12 22:42:50.854428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '671206b30136'
down_revision = 'bbc6b0512ae2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
