"""Init

Revision ID: a78868cea02b
Revises: 406dc6d1479c
Create Date: 2022-12-13 09:02:42.991274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a78868cea02b'
down_revision = '406dc6d1479c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
