"""Init

Revision ID: bbc6b0512ae2
Revises: 
Create Date: 2022-12-12 22:30:41.254906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbc6b0512ae2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Название лекарства', sa.String(length=100), nullable=True),
    sa.Column('Производитель', sa.String(length=100), nullable=True),
    sa.Column('Цена (руб.)', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Название лекарства')
    )
    op.create_index(op.f('ix_medicines_id'), 'medicines', ['id'], unique=False)
    op.create_table('pharmacy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Название аптеки', sa.String(length=100), nullable=True),
    sa.Column('Адрес аптеки', sa.String(length=100), nullable=True),
    sa.Column('Номер телефона', sa.String(length=11), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Название аптеки')
    )
    op.create_index(op.f('ix_pharmacy_id'), 'pharmacy', ['id'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Дата составления заявки', sa.DateTime(), nullable=True),
    sa.Column('Номер аптеки', sa.Integer(), nullable=True),
    sa.Column('Дата выполнения заявки', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['Номер аптеки'], ['pharmacy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    op.create_table('purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('номер заявки', sa.Integer(), nullable=True),
    sa.Column('код лекарства', sa.Integer(), nullable=True),
    sa.Column('количество (шт.)', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['код лекарства'], ['medicines.id'], ),
    sa.ForeignKeyConstraint(['номер заявки'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchases_id'), 'purchases', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchases_id'), table_name='purchases')
    op.drop_table('purchases')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_pharmacy_id'), table_name='pharmacy')
    op.drop_table('pharmacy')
    op.drop_index(op.f('ix_medicines_id'), table_name='medicines')
    op.drop_table('medicines')
    # ### end Alembic commands ###
