"""Init

Revision ID: d193258315ee
Revises: 2e8d5992aacb
Create Date: 2022-12-13 09:20:21.076282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd193258315ee'
down_revision = '2e8d5992aacb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
